### ISSUE TITLE
Error message on the dashboard is JSON and references 

### ISSUE THREAD

**Issue by nmummau** [mailslurp/documentation#1]
The error in this alert just displays raw JSON. Should be cleaned up to display human readable error message. Also it has a grammar mistake: **Your may have exceeded** 

The error also references the SDK method. For a non-technical user, this would not be helpful. Instead it would be best to tell them that they are limited to n number of inboxes per month based on their plan.

![image](https://user-images.githubusercontent.com/10524529/70368935-71f4c000-187f-11ea-8bb4-23a490144a0c.png)

**Comment by jackmahoney** [comment]
Thanks for your feedback @nmummau we appreciate it! We will take this on board
